version: '3.2'

services:
  jska:
    build:
      context: .
      args:
        ARG_VERSION_MAJOR: ${VERSION_MAJOR}
        ARG_VERSION_MINOR: ${VERSION_MINOR}
        ARG_VERSION_PATCH: ${VERSION_PATCH}
        ARG_RELEASE: ${RELEASE}
        ARG_NAME_COLUMN: ${NAME_COLUMN}
        ARG_TIME_COLUMN: ${TIME_COLUMN}
        ARG_VALUE_COLUMN: ${VALUE_COLUMN}
    restart: always
    volumes:
      - type: bind
        source: ${TELEMETRY_ARCHIVE}
        target: /srv/telemetry/archive/
      - type: bind
        source: ${STAGING_DIRECTORY}
        target: /srv/telemetry/staging/
    ports:
      - "9232:9232"
    environment:
      - "WORKERS=${WORKERS}"
networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}